openapi: 3.0.3
info:
  title: API сервиса Midray
  description: |
    С помощью этого API можно выгрузить данные Росстата
    и прочие рассчитанные данные для дашбордов,
    запросить прогноз по численности населения
    и AI справку.
  version: 1.0.0
paths:
  /api/v1/geo:
    get:
      summary: Получение древовидной структуры РФ.
      description: |
        Древовидная структура представлена в виде:
        1. Субъект РФ
        2. Муниципалитет верхнего уровня
        3. Муниципалитет нижнего уровня.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FederalSubject'
              example:
                - name: "Алтайский край"
                  code: 1
                  upper_municipalities: []
                - name: "Краснодарский край"
                  code: 3
                  upper_municipalities: []

  /api/v1/rosstat:
    get:
      summary: Получение данных Росстата.
      parameters:
        - name: fields
          in: query
          required: true
          description: Показатели для выгрузки.
          schema:
            type: array
            items:
              type: string
              enum: [year, population, birth, death, arrival, departure, age,
                    male, female, land_area, avg_salary,
                    medical_facilities, schools, housing_commissioned] 
          style: form
          explode: true
          example: ["population", "birth", "death"]
        - name: codes
          in: query
          required: false
          description: |
            Коды муниципалитетов и субъектов РФ.
            Если параметр не указан, выгружаются общие данные по РФ.
          schema:
            type: array
            items:
              type: integer
          style: form
          explode: true
          example: [1, 3, 4]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RosstatResponse'
              example:
                - code: 1
                  by_year:
                    - year: 2020
                      population: 2300000
                      birth: 20000
                      death: 25000
                    - year: 2021
                      population: 2310000
                      birth: 19000
                      death: 24000
                - code: 2
                  by_year:
                    - year: 2020
                      population: 146000000
                      birth: 1400000
                      death: 1800000
        '400':
          description: |
            Отсутствует обязательный параметр
            или указанный код не существует.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "field 'fields' is required"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Описание ошибки
      example:
        error: "field 'fields' is required"

    LowerMunicipality:
      type: object
      description: Муниципалитет нижнего уровня.
      properties:
        name:
          type: string
          description: Наименование муниципалитета нижнего уровня.
        code:
          type: integer
          description: Код муниципалитета нижнего уровня.
      required:
        - name
        - code
      example:
        name: "Центральный район"
        code: 1000

    UpperMunicipality:
      type: object
      description: Муниципалитет верхнего уровня.
      properties:
        name:
          type: string
          description: Наименование муниципалитета верхнего уровня.
        code:
          type: integer
          description: Код муниципалитета верхнего уровня.
        lower_municipalities:
          type: array
          description: Муниципалитеты нижнего уровня.
          items:
            $ref: '#/components/schemas/LowerMunicipality'
      required:
        - name
        - code
        - lower_municipalities
      example:
        name: "г. Барнаул"
        code: 100
        lower_municipalities:
          - name: "Центральный район"
            code: 1000
          - name: "Ленинский район"
            code: 1001

    FederalSubject:
      type: object
      description: Субъект РФ.
      properties:
        name:
          type: string
          description: Наименование субъекта РФ.
        code:
          type: integer
          description: Код субъекта РФ.
        upper_municipalities:
          type: array
          description: Муниципалитеты верхнего уровня.
          items:
            $ref: '#/components/schemas/UpperMunicipality'
      required:
        - name
        - code
        - upper_municipalities
      example:
        name: "Алтайский край"
        code: 1
        upper_municipalities:
          - name: "г. Барнаул"
            code: 100
            lower_municipalities: []
        
    RosstatByAge:
      type: object
      properties:
        age:
          type: integer
          description: Возраст.
        male:
          type: integer
          description: Численность мужчин указанного возраста.
        female:
          type: integer
          description: Численность женщин указанного возраста.
      required:
        - age
        - male
        - female
      example:
        age: 25
        male: 50000
        female: 48000

    RosstatByYear:
      type: object
      properties:
        year:
          type: integer
          description: Указанный год
        population:
          type: integer
          description: Численность населения за указанный год.
          nullable: true
        birth:
          type: integer
          description: Численность рожденных за указанный год.
          nullable: true
        death:
          type: integer
          description: Численность умерших за указанный год.
          nullable: true
        arrival:
          type: integer
          description: Численность прибывших за указанный год.
          nullable: true
        departure:
          type: integer
          description: Численность выбывших за указанный год.
          nullable: true
        male:
          type: integer
          description: Численность мужчин за указанный год.
          nullable: true
        female:
          type: integer
          description: Численность женщин за указанный год.
          nullable: true
        land_area:
          type: number
          format: float
          description: Земельная площадь субъекта РФ или муниципалитета за указанный год.
          nullable: true
        avg_salary:
          type: number
          format: float
          description: |
            Средняя заработная плата по субъекту РФ или муниципалитету
            за указанный год.
          nullable: true
        medical_facilities:
          type: integer
          description: |
            Число медицинских учреждений в субъекте РФ или муниципалитете
            за указанный год.
          nullable: true
        schools:
          type: integer
          description: |
            Число школ в субъекте РФ или муниципалитете
            за указанный год.
          nullable: true
        housing_commissioned:
          type: integer
          description: |
            Число введенных в эксплуатацию жилых объектов в субъекте РФ или муниципалитете
            за указанный год.
          nullable: true
        by_age:
          type: array
          description: Численность мужчин и женщин по возрасту за год.
          nullable: true
          items:
            $ref: '#/components/schemas/RosstatByAge'
      example:
        year: 2020
        population: 2300000
        birth: 20000
        death: 25000
        arrival: 15000
        departure: 12000

    Rosstat:
      type: object
      properties:
        code:
          type: integer
          description: |
            Код субъекта РФ или муниципалитета.
            РФ использует код 0.
        by_year:
          type: array
          description: |
            Данные Росстата по годам.
          items:
            $ref: '#/components/schemas/RosstatByYear'
      required:
        - code
        - by_year
      example:
        code: 1
        by_year:
          - year: 2020
            population: 2300000
            birth: 20000
            death: 25000
          - year: 2021
            population: 2310000
            birth: 19000
            death: 24000

    RosstatResponse:
      type: array
      items:
        $ref: '#/components/schemas/Rosstat'
      example:
        - code: 1
          by_year:
            - year: 2020
              population: 2300000
              birth: 20000
              death: 25000
        - code: 0
          by_year:
            - year: 2020
              population: 146000000
              birth: 1400000
              death: 1800000